<?php return array(
    'root' => array(
        'name' => 'freesense/freesense',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../../../../../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'freesense/freesense' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../../../../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mikehaertl/php-shellcommand' => array(
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'reference' => 'e79ea528be155ffdec6f3bf1a4a46307bb49e545',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mikehaertl/php-shellcommand',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nette/utils' => array(
            'pretty_version' => 'v4.1.5',
            'version' => '4.1.5.0',
            'reference' => 'b043439dbdf954e6c28b5ea7e34b0100f83165e0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'simplepie/simplepie' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'reference' => '76cccb1b2c5dcaf44f304c925ab30c0f48643992',
            'type' => 'library',
            'install_path' => __DIR__ . '/../simplepie/simplepie',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache' => array(
            'pretty_version' => 'v8.1.8',
            'version' => '8.1.8.0',
            'reference' => '8888daf06a2fc8440346215d3b52f3c611cc486d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache-contracts' => array(
            'pretty_version' => 'v3.7.1',
            'version' => '3.7.1.0',
            'reference' => '9789738bc19af1106dc54d6afba9a0b467516cf2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0|3.0',
            ),
        ),
        'symfony/console' => array(
            'pretty_version' => 'v8.1.8',
            'version' => '8.1.8.0',
            'reference' => '4b81146e3ee248ea969186f85499b54fbc78db08',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.7.1',
            'version' => '3.7.1.0',
            'reference' => 'f3202fa1b5097b0af062dc978b32ecf63404e31d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.37.0',
            'version' => '1.37.0.0',
            'reference' => '141046a8f9477948ff284fa65be2095baafb94f2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-deepclone' => array(
            'pretty_version' => 'v1.43.0',
            'version' => '1.43.0.0',
            'reference' => '8db92c5508a3f7f82d8688d32f0a4868a26e58ad',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-deepclone',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.43.0',
            'version' => '1.43.0.0',
            'reference' => '5cac8f4db97208823aa353f59a01faad2da52c75',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.43.0',
            'version' => '1.43.0.0',
            'reference' => 'ebd57ccc7edb93d632e184efbe7693d2517bab3b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.43.0',
            'version' => '1.43.0.0',
            'reference' => '4d5d331bf731e0aedbc6b2f5e61135b7b7996a72',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php85' => array(
            'pretty_version' => 'v1.43.0',
            'version' => '1.43.0.0',
            'reference' => '86a42cbcc07adc331481a5ab310a4024bfc227f6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php85',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.7.3',
            'version' => '3.7.3.0',
            'reference' => '15e6a07ec2a2c75ceb1b21dd98105ee8456d2257',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v8.1.7',
            'version' => '8.1.7.0',
            'reference' => 'd950140b5f56f31901e5b7a0c04ffc3a3deb943c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v8.1.6',
            'version' => '8.1.6.0',
            'reference' => '802362f41128c430fd6685491e1fb72127fae78a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
